#cloud-config

hostname: ${hostname}
fqdn: ${fqdn}
manage_etc_hosts: true

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates

apt:
  sources:
    docker.list:
      source: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
      keyid: 58118E89F3A912897C070ADBF76221572C52609D
      keyserver: hkp://ha.pool.sks-keyservers.net:80

write_files:
  - path: /etc/ecs.conf
    content: |
      ECS_CLUSTER=${ecs_cluster}
      ECS_LOGFILE=/var/log/ecs/ecs-agent.log
      ECS_DATADIR=/var/lib/ecs/
      ECS_ENABLE_TASK_IAM_ROLE=true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true

runcmd:
  # install docker
  - apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual
  - apt-get install -y docker-engine
  # install ecs agent
  - mkdir -p /var/lib/ecs /var/log/ecs
  - sysctl -w net.ipv4.conf.all.route_localnet=1
  - iptables -t nat -A PREROUTING -d 169.254.170.2 -p tcp --dport 80 -j DNAT --to-destination 127.0.0.1:51679
  - iptables -t nat -A OUTPUT -d 169.254.170.2 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 51679
  - docker pull amazon/amazon-ecs-agent:latest
  - docker run -d --name ecs-agent --restart=on-failure:10 --env-file=/etc/ecs.conf --volume=/var/run/docker.sock:/var/run/docker.sock --volume=/var/log/ecs:/var/log/ecs --volume=/var/lib/ecs:/var/lib/ecs --net=host amazon/amazon-ecs-agent:latest
